### PR TITLE
feat: add transaction v3 support

### LINKED ISSUE #1: feat: add support for transaction v3 schema
In order to be able to send transactions to a Planetmint node, the assets built during transaction instantiation needs to comply with [transaction v3.0 ](https://docs.planetmint.io/using-planetmint#transaction-v3.0).

That means:
- [x] updating the methods related to assets in [Transaction](https://github.com/planetmint/planetmint-driver-ts/blob/main/src/transaction.js)
- [x] updating the [Transaction types definitions](https://github.com/planetmint/planetmint-driver-ts/blob/main/types/transaction.d.ts)
- [x] adding libs/helpers (?) to generate `CID` for asset.data and metadata (at least in examples and tests)
- [ ] adding runtime validation of the inputs ? With `class-validator` ? (this item would be more relevant after migration to Typescript)
- [x] obviously adding/updating test suites

References:
- creating CID with [multiformats lib](https://github.com/multiformats/js-multiformats)

### PR DESCRIPTION
**Pull request by getlarge**
## Solution

Migrate BCDB driver to add support for new transaction schema as outlined [here](https://github.com/planetmint/planetmint-driver-ts/issues/1)

## Issues Resolved

Resolves #1

## Checklist

- [ ] version number increased
- [ ] CHANGELOG.md updated
- [x] unit test added
- [x] example updated or added

### CODE REVIEW

**Comment by getlarge** [comment]
In order to finish this PR i see the following pending items:
- [x] docker image available for Planetmint
- [x] clarifying what's the response expected from `api/v1/blocks?transaction_id=XXXX` as in my local setup i got responses with a schema like `[ [ string, string, number, string[] ] ]`. Which following a discussion with @eckelj , is not the expected bahaviour.
- [x] for some unknown reason the workflow is not triggered, still need to check that out... (default branch was invalid)
- [ ] should the docs still be generated for readthedocs ? if yes i still need to update the license and naming.

**Comment by eckelj** [comment]
@getlarge  you're TX are expected to fail.
you send
metadata != type string (CID string) and asset needs to be renamed to assets and contain a list/array of objects like
{ "data" : cidstring} or  { "id": asset-id } for creating or transferring transactions as mentioned in the specs that we wrote at
https://docs.planetmint.io/using-planetmint#transaction-v3.0

container images will be published at https://github.com/planetmint/planetmint/pkgs/container/planetmint a first is out. we are working on migrations towards ARM for the containers.

The currently supported schemas can be inspected at: https://github.com/planetmint/transactions/tree/main/transactions/common/schema/v3.0

**Comment by getlarge** [comment]
> @getlarge you're TX are expected to fail. you send metadata != type string (CID string) and asset needs to be renamed to assets and contain a list/array of objects like { "data" : cidstring} or { "id": asset-id } for creating or transferring transactions as mentioned in the specs that we wrote at https://docs.planetmint.io/using-planetmint#transaction-v3.0
> 
> container images will be published at https://github.com/planetmint/planetmint/pkgs/container/planetmint a first is out. we are working on migrations towards ARM for the containers.
> 
> The currently supported schemas can be inspected at: https://github.com/planetmint/transactions/tree/main/transactions/common/schema/v3.0

I added support for the new schema :
-  in the static methods of the `Transaction` class, [`makeTransaction`](https://github.com/planetmint/planetmint-driver-ts/blob/feat-add-transaction-v3-support/src/transaction.js#L53) and by extension `makeCreateTransaction` and `makeTransferTransaction`
- in the `Transaction` [type definitions](https://github.com/planetmint/planetmint-driver-ts/blob/feat-add-transaction-v3-support/types/transaction.d.ts#L65)
- in the test i also created [valid mocked assets and metadata](https://github.com/planetmint/planetmint-driver-ts/blob/feat-add-transaction-v3-support/test/constants.js#L32) that were successfully sent to my local Planetmint node

**Review by LaurentMontBlanc — APPROVED** [review]

**Comment by getlarge** [comment]
@eckelj  Tests are passing when using the latest Docker image.
The question about documentation generation still remain unsolved ?
Should we postpone for another PR?

**Comment by eckelj** [comment]
@getlarge yes. let's change the docs in a new PR

**Pull request merged**
